name: Build + Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: tinkerpop/gremlin-server
        ports:
          - 8182:8182

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Setup .NET Core 3.1.6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.106
        source-url: https://nuget.pkg.github.com/exram/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Push NuGet packages
      if: github.event_name == 'push'
      run: dotnet nuget push **/*.nupkg --no-symbols true --skip-duplicate
