name: Build + Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: tinkerpop/gremlin-server
        ports:
          - 8182:8182

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Setup .NET Core 5.0.100
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --verbosity normal -p:SkipIntegrationTests=${{ github.event_name == 'pull_request'}}

    - name: Push NuGet packages to GitHub packages
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: dotnet nuget push **/*.nupkg
        --source https://nuget.pkg.github.com/exram/index.json
        --api-key ${{ secrets.GITHUB_TOKEN }}
        --no-symbols true
        --skip-duplicate
      
    - name: Push NuGet packages to NuGet.org
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/rel' }}
      run: dotnet nuget push **/*.nupkg
        --source https://api.nuget.org/v3/index.json
        --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
        --no-symbols true
        --skip-duplicate
        
    - uses: dotnet/nbgv@master
      id: nbgv
      with:
        path: src

    - name: Bump version and push tag
      if: github.ref == 'refs/heads/rel'
      uses: anothrNick/github-tag-action@1.22.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ steps.nbgv.outputs.SemVer2 }}
        RELEASE_BRANCHES: .*
